interface DemoDisclaimerProps {
  vertical: string;
}

export function DemoDisclaimer({ vertical }: DemoDisclaimerProps) {
  const isLegal = vertical === 'legal';

  return (
    <div className="mt-8 border-t border-border pt-4">
      <p className="text-xs text-muted-foreground">
        {isLegal ? (
          <>
            <strong>Legal Disclaimer:</strong> All content generated in this demo is fictional and
            for demonstration purposes only. It does not constitute legal advice and should not be
            relied upon for any legal decision-making. Consult a qualified attorney for legal guidance.
          </>
        ) : (
          <>
            <strong>Demo Disclaimer:</strong> This is an interactive demonstration of AI capabilities.
            Responses are generated by AI and may not be perfectly accurate. For production implementations,
            contact BenchworksAI for a customized solution.
          </>
        )}
      </p>
    </div>
  );
}
