// Disposable email domain blocklist (~50 common providers)
export const DISPOSABLE_DOMAINS = new Set([
  'mailinator.com',
  'guerrillamail.com',
  'guerrillamail.net',
  'tempmail.com',
  'throwaway.email',
  'temp-mail.org',
  'fakeinbox.com',
  'sharklasers.com',
  'grr.la',
  'guerrillamailblock.com',
  'pokemail.net',
  'spam4.me',
  'bccto.me',
  'trashmail.com',
  'trashmail.me',
  'trashmail.net',
  'yopmail.com',
  'yopmail.fr',
  'nada.email',
  'maildrop.cc',
  'dispostable.com',
  'mailnesia.com',
  'tempail.com',
  'tempr.email',
  'discard.email',
  'discardmail.com',
  'disposableemailaddresses.emailmiser.com',
  'mailcatch.com',
  'getairmail.com',
  'meltmail.com',
  'harakirimail.com',
  'mailexpire.com',
  'tempinbox.com',
  'mytemp.email',
  'mohmal.com',
  'burnermail.io',
  'inboxbear.com',
  'mailsac.com',
  'mintemail.com',
  'jetable.org',
  'emailondeck.com',
  'getnada.com',
  'tmpmail.net',
  'tmpmail.org',
  'crazymailing.com',
  'armyspy.com',
  'dayrep.com',
  'einrot.com',
  'fleckens.hu',
  'jourrapide.com',
]);

export function isDisposableEmail(email: string): boolean {
  const domain = email.split('@')[1]?.toLowerCase();
  if (!domain) return false;
  return DISPOSABLE_DOMAINS.has(domain);
}
