import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 11, lineHeight: 1.5 },
  header: { marginBottom: 20 },
  title: { fontSize: 22, fontFamily: 'Helvetica-Bold', marginBottom: 4 },
  subtitle: { fontSize: 12, color: '#64748b' },
  divider: { borderBottomWidth: 1, borderBottomColor: '#e2e8f0', marginVertical: 16 },
  sectionTitle: { fontSize: 14, fontFamily: 'Helvetica-Bold', marginBottom: 6, color: '#1e293b' },
  body: { fontSize: 11, color: '#334155', lineHeight: 1.6 },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, fontSize: 8, color: '#94a3b8', textAlign: 'center' },
  metaRow: { flexDirection: 'row', marginBottom: 2 },
  metaLabel: { fontSize: 10, color: '#64748b', width: 100 },
  metaValue: { fontSize: 10, color: '#334155' },
});

interface CompetitiveReportPDFProps {
  businessName: string;
  competitors: string[];
  vertical: string;
  reportText: string;
  generatedAt: string;
}

export function CompetitiveReportPDF({
  businessName,
  competitors,
  vertical,
  reportText,
  generatedAt,
}: CompetitiveReportPDFProps) {
  // Split report into sections by markdown-style headers
  const sections = parseSections(reportText);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.title}>Competitive Analysis Report</Text>
          <Text style={styles.subtitle}>{businessName}</Text>
        </View>

        {/* Meta */}
        <View style={{ marginBottom: 12 }}>
          <View style={styles.metaRow}>
            <Text style={styles.metaLabel}>Industry:</Text>
            <Text style={styles.metaValue}>{vertical}</Text>
          </View>
          {competitors.length > 0 && (
            <View style={styles.metaRow}>
              <Text style={styles.metaLabel}>Competitors:</Text>
              <Text style={styles.metaValue}>{competitors.join(', ')}</Text>
            </View>
          )}
          <View style={styles.metaRow}>
            <Text style={styles.metaLabel}>Generated:</Text>
            <Text style={styles.metaValue}>{generatedAt}</Text>
          </View>
        </View>

        <View style={styles.divider} />

        {/* Report body */}
        {sections.map((section, i) => (
          <View key={i} style={{ marginBottom: 12 }}>
            {section.heading && <Text style={styles.sectionTitle}>{section.heading}</Text>}
            <Text style={styles.body}>{section.content}</Text>
          </View>
        ))}

        {/* Footer */}
        <Text style={styles.footer}>
          Generated by BenchworksAI — for demonstration purposes only. Not a substitute for professional analysis.
        </Text>
      </Page>
    </Document>
  );
}

function parseSections(text: string): { heading: string | null; content: string }[] {
  const lines = text.split('\n');
  const sections: { heading: string | null; content: string }[] = [];
  let currentHeading: string | null = null;
  let currentContent: string[] = [];

  for (const line of lines) {
    const headerMatch = line.match(/^#{1,3}\s+(.+)/);
    if (headerMatch) {
      if (currentContent.length > 0 || currentHeading) {
        sections.push({ heading: currentHeading, content: currentContent.join('\n').trim() });
      }
      currentHeading = headerMatch[1].trim();
      currentContent = [];
    } else {
      currentContent.push(line);
    }
  }

  if (currentContent.length > 0 || currentHeading) {
    sections.push({ heading: currentHeading, content: currentContent.join('\n').trim() });
  }

  return sections.filter((s) => s.content.length > 0 || s.heading);
}
